/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2099.99
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package jetbrains.youtrack.client.api;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Represents a build - a single element of a builds bundle.
 */
@Schema(description = "Represents a build - a single element of a builds bundle.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-04T14:25:38.465627+03:00[Europe/Moscow]")
public class BuildBundleElement extends BundleElement {
  @JsonProperty("assembleDate")
  private Long assembleDate = null;

  public BuildBundleElement assembleDate(Long assembleDate) {
    this.assembleDate = assembleDate;
    return this;
  }

   /**
   * Get assembleDate
   * @return assembleDate
  **/
  @Schema(description = "")
  public Long getAssembleDate() {
    return assembleDate;
  }

  public void setAssembleDate(Long assembleDate) {
    this.assembleDate = assembleDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuildBundleElement buildBundleElement = (BuildBundleElement) o;
    return Objects.equals(this.assembleDate, buildBundleElement.assembleDate) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assembleDate, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuildBundleElement {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    assembleDate: ").append(toIndentedString(assembleDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
