/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2099.99
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package jetbrains.youtrack.client.api;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Sets a card color based on a value of some custom field.
 */
@Schema(description = "Sets a card color based on a value of some custom field.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-04T14:25:38.465627+03:00[Europe/Moscow]")
public class FieldBasedColorCoding extends ColorCoding {
  @JsonProperty("prototype")
  private CustomField prototype = null;

  public FieldBasedColorCoding prototype(CustomField prototype) {
    this.prototype = prototype;
    return this;
  }

   /**
   * Get prototype
   * @return prototype
  **/
  @Schema(description = "")
  public CustomField getPrototype() {
    return prototype;
  }

  public void setPrototype(CustomField prototype) {
    this.prototype = prototype;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FieldBasedColorCoding fieldBasedColorCoding = (FieldBasedColorCoding) o;
    return Objects.equals(this.prototype, fieldBasedColorCoding.prototype) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prototype, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FieldBasedColorCoding {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    prototype: ").append(toIndentedString(prototype)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
