/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2099.99
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package jetbrains.youtrack.client.api;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;

/**
 * Lets you set a color for a card based on its project.
 */
@Schema(description = "Lets you set a color for a card based on its project.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-04T14:25:38.465627+03:00[Europe/Moscow]")
public class ProjectBasedColorCoding extends ColorCoding {
  @JsonProperty("projectColors")
  private List<ProjectColor> projectColors = null;

  public ProjectBasedColorCoding projectColors(List<ProjectColor> projectColors) {
    this.projectColors = projectColors;
    return this;
  }

  public ProjectBasedColorCoding addProjectColorsItem(ProjectColor projectColorsItem) {
    if (this.projectColors == null) {
      this.projectColors = new ArrayList<ProjectColor>();
    }
    this.projectColors.add(projectColorsItem);
    return this;
  }

   /**
   * Get projectColors
   * @return projectColors
  **/
  @Schema(description = "")
  public List<ProjectColor> getProjectColors() {
    return projectColors;
  }

  public void setProjectColors(List<ProjectColor> projectColors) {
    this.projectColors = projectColors;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectBasedColorCoding projectBasedColorCoding = (ProjectBasedColorCoding) o;
    return Objects.equals(this.projectColors, projectBasedColorCoding.projectColors) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectColors, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectBasedColorCoding {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    projectColors: ").append(toIndentedString(projectColors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
