/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2099.99
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package jetbrains.youtrack.client.api;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeId;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * Represents the Resource Sharing (CORS) configuration of the service.
 */
@Schema(description = "Represents the Resource Sharing (CORS) configuration of the service.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-04T14:25:38.465627+03:00[Europe/Moscow]")@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "$type", visible = true )
@JsonSubTypes({
})

public class RestCorsSettings {
  @JsonProperty("allowedOrigins")
  private List<String> allowedOrigins = null;

  @JsonProperty("allowAllOrigins")
  private Boolean allowAllOrigins = null;

  @JsonProperty("id")
  private String id = null;

  @JsonTypeId
  private String $type = null;

  public RestCorsSettings allowedOrigins(List<String> allowedOrigins) {
    this.allowedOrigins = allowedOrigins;
    return this;
  }

  public RestCorsSettings addAllowedOriginsItem(String allowedOriginsItem) {
    if (this.allowedOrigins == null) {
      this.allowedOrigins = new ArrayList<String>();
    }
    this.allowedOrigins.add(allowedOriginsItem);
    return this;
  }

   /**
   * Get allowedOrigins
   * @return allowedOrigins
  **/
  @Schema(description = "")
  public List<String> getAllowedOrigins() {
    return allowedOrigins;
  }

  public void setAllowedOrigins(List<String> allowedOrigins) {
    this.allowedOrigins = allowedOrigins;
  }

  public RestCorsSettings allowAllOrigins(Boolean allowAllOrigins) {
    this.allowAllOrigins = allowAllOrigins;
    return this;
  }

   /**
   * Get allowAllOrigins
   * @return allowAllOrigins
  **/
  @Schema(description = "")
  public Boolean isAllowAllOrigins() {
    return allowAllOrigins;
  }

  public void setAllowAllOrigins(Boolean allowAllOrigins) {
    this.allowAllOrigins = allowAllOrigins;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

   /**
   * Get $type
   * @return $type
  **/
  @Schema(description = "")
  public String get$Type() {
    return $type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestCorsSettings restCorsSettings = (RestCorsSettings) o;
    return Objects.equals(this.allowedOrigins, restCorsSettings.allowedOrigins) &&
        Objects.equals(this.allowAllOrigins, restCorsSettings.allowAllOrigins) &&
        Objects.equals(this.id, restCorsSettings.id) &&
        Objects.equals(this.$type, restCorsSettings.$type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowedOrigins, allowAllOrigins, id, $type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestCorsSettings {\n");
    
    sb.append("    allowedOrigins: ").append(toIndentedString(allowedOrigins)).append("\n");
    sb.append("    allowAllOrigins: ").append(toIndentedString(allowAllOrigins)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    $type: ").append(toIndentedString($type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
