/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2099.99
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package jetbrains.youtrack.client.api;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeId;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Represents time tracking settings in the user&#x27;s profile.
 */
@Schema(description = "Represents time tracking settings in the user's profile.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-04T14:25:38.465627+03:00[Europe/Moscow]")@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "$type", visible = true )
@JsonSubTypes({
})

public class TimeTrackingUserProfile {
  @JsonProperty("periodFormat")
  private PeriodFieldFormat periodFormat = null;

  @JsonProperty("id")
  private String id = null;

  @JsonTypeId
  private String $type = null;

  public TimeTrackingUserProfile periodFormat(PeriodFieldFormat periodFormat) {
    this.periodFormat = periodFormat;
    return this;
  }

   /**
   * Get periodFormat
   * @return periodFormat
  **/
  @Schema(description = "")
  public PeriodFieldFormat getPeriodFormat() {
    return periodFormat;
  }

  public void setPeriodFormat(PeriodFieldFormat periodFormat) {
    this.periodFormat = periodFormat;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

   /**
   * Get $type
   * @return $type
  **/
  @Schema(description = "")
  public String get$Type() {
    return $type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeTrackingUserProfile timeTrackingUserProfile = (TimeTrackingUserProfile) o;
    return Objects.equals(this.periodFormat, timeTrackingUserProfile.periodFormat) &&
        Objects.equals(this.id, timeTrackingUserProfile.id) &&
        Objects.equals(this.$type, timeTrackingUserProfile.$type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(periodFormat, id, $type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeTrackingUserProfile {\n");
    
    sb.append("    periodFormat: ").append(toIndentedString(periodFormat)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    $type: ").append(toIndentedString($type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
