/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2099.99
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package jetbrains.youtrack.client.api;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import static com.atlassian.renderer.v2.components.HtmlEscaper.escapeAll;

/**
 * Represents a field value or values, parameterizing agile column.
 */
@Schema(description = "Represents a field value or values, parameterizing agile column.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-04T14:25:38.465627+03:00[Europe/Moscow]")
public class AgileColumnFieldValue extends DatabaseAttributeValue {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("isResolved")
  private Boolean isResolved = null;

  public AgileColumnFieldValue name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return escapeAll(name, false);
  }

  public void setName(String name) {
    this.name = name;
  }

   /**
   * Get isResolved
   * @return isResolved
  **/
  @Schema(description = "")
  public Boolean isIsResolved() {
    return isResolved;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgileColumnFieldValue agileColumnFieldValue = (AgileColumnFieldValue) o;
    return Objects.equals(this.name, agileColumnFieldValue.name) &&
        Objects.equals(this.isResolved, agileColumnFieldValue.isResolved) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, isResolved, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgileColumnFieldValue {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isResolved: ").append(toIndentedString(isResolved)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
