/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2099.99
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package jetbrains.youtrack.client.api;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeId;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Represents the Visual settings of the YouTrack service.
 */
@Schema(description = "Represents the Visual settings of the YouTrack service.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-04T14:25:38.465627+03:00[Europe/Moscow]")@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "$type", visible = true )
@JsonSubTypes({
})

public class AppearanceSettings {
  @JsonProperty("timeZone")
  private TimeZoneDescriptor timeZone = null;

  @JsonProperty("dateFieldFormat")
  private DateFormatDescriptor dateFieldFormat = null;

  @JsonProperty("logo")
  private Logo logo = null;

  @JsonProperty("id")
  private String id = null;

  @JsonTypeId
  private String $type = null;

  public AppearanceSettings timeZone(TimeZoneDescriptor timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * Get timeZone
   * @return timeZone
  **/
  @Schema(description = "")
  public TimeZoneDescriptor getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(TimeZoneDescriptor timeZone) {
    this.timeZone = timeZone;
  }

  public AppearanceSettings dateFieldFormat(DateFormatDescriptor dateFieldFormat) {
    this.dateFieldFormat = dateFieldFormat;
    return this;
  }

   /**
   * Get dateFieldFormat
   * @return dateFieldFormat
  **/
  @Schema(description = "")
  public DateFormatDescriptor getDateFieldFormat() {
    return dateFieldFormat;
  }

  public void setDateFieldFormat(DateFormatDescriptor dateFieldFormat) {
    this.dateFieldFormat = dateFieldFormat;
  }

  public AppearanceSettings logo(Logo logo) {
    this.logo = logo;
    return this;
  }

   /**
   * Get logo
   * @return logo
  **/
  @Schema(description = "")
  public Logo getLogo() {
    return logo;
  }

  public void setLogo(Logo logo) {
    this.logo = logo;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

   /**
   * Get $type
   * @return $type
  **/
  @Schema(description = "")
  public String get$Type() {
    return $type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppearanceSettings appearanceSettings = (AppearanceSettings) o;
    return Objects.equals(this.timeZone, appearanceSettings.timeZone) &&
        Objects.equals(this.dateFieldFormat, appearanceSettings.dateFieldFormat) &&
        Objects.equals(this.logo, appearanceSettings.logo) &&
        Objects.equals(this.id, appearanceSettings.id) &&
        Objects.equals(this.$type, appearanceSettings.$type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeZone, dateFieldFormat, logo, id, $type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppearanceSettings {\n");
    
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    dateFieldFormat: ").append(toIndentedString(dateFieldFormat)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    $type: ").append(toIndentedString($type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
