/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2099.99
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package jetbrains.youtrack.client.api;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeId;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents users that are subscribed to notifications about the issue.
 */
@Schema(description = "Represents users that are subscribed to notifications about the issue.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-04T14:25:38.465627+03:00[Europe/Moscow]")@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "$type", visible = true )
@JsonSubTypes({
})

public class IssueWatchers {
  @JsonProperty("hasStar")
  private Boolean hasStar = null;

  @JsonProperty("issueWatchers")
  private List<IssueWatcher> issueWatchers = null;

  @JsonProperty("duplicateWatchers")
  private List<IssueWatcher> duplicateWatchers = null;

  @JsonProperty("id")
  private String id = null;

  @JsonTypeId
  private String $type = null;

  public IssueWatchers hasStar(Boolean hasStar) {
    this.hasStar = hasStar;
    return this;
  }

   /**
   * Get hasStar
   * @return hasStar
  **/
  @Schema(description = "")
  public Boolean isHasStar() {
    return hasStar;
  }

  public void setHasStar(Boolean hasStar) {
    this.hasStar = hasStar;
  }

  public IssueWatchers issueWatchers(List<IssueWatcher> issueWatchers) {
    this.issueWatchers = issueWatchers;
    return this;
  }

  public IssueWatchers addIssueWatchersItem(IssueWatcher issueWatchersItem) {
    if (this.issueWatchers == null) {
      this.issueWatchers = new ArrayList<IssueWatcher>();
    }
    this.issueWatchers.add(issueWatchersItem);
    return this;
  }

   /**
   * Get issueWatchers
   * @return issueWatchers
  **/
  @Schema(description = "")
  public List<IssueWatcher> getIssueWatchers() {
    return issueWatchers;
  }

  public void setIssueWatchers(List<IssueWatcher> issueWatchers) {
    this.issueWatchers = issueWatchers;
  }

   /**
   * Get duplicateWatchers
   * @return duplicateWatchers
  **/
  @Schema(description = "")
  public List<IssueWatcher> getDuplicateWatchers() {
    return duplicateWatchers;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

   /**
   * Get $type
   * @return $type
  **/
  @Schema(description = "")
  public String get$Type() {
    return $type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueWatchers issueWatchers = (IssueWatchers) o;
    return Objects.equals(this.hasStar, issueWatchers.hasStar) &&
        Objects.equals(this.issueWatchers, issueWatchers.issueWatchers) &&
        Objects.equals(this.duplicateWatchers, issueWatchers.duplicateWatchers) &&
        Objects.equals(this.id, issueWatchers.id) &&
        Objects.equals(this.$type, issueWatchers.$type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hasStar, issueWatchers, duplicateWatchers, id, $type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueWatchers {\n");
    
    sb.append("    hasStar: ").append(toIndentedString(hasStar)).append("\n");
    sb.append("    issueWatchers: ").append(toIndentedString(issueWatchers)).append("\n");
    sb.append("    duplicateWatchers: ").append(toIndentedString(duplicateWatchers)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    $type: ").append(toIndentedString($type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
