/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2099.99
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package jetbrains.youtrack.client.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeId;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * IssueCustomField
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-04T14:25:38.465627+03:00[Europe/Moscow]")@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "$type", visible = true )
@JsonSubTypes({
  @JsonSubTypes.Type(value = SingleBuildIssueCustomField.class, name = "SingleBuildIssueCustomField"),
  @JsonSubTypes.Type(value = MultiBuildIssueCustomField.class, name = "MultiBuildIssueCustomField"),
  @JsonSubTypes.Type(value = SingleUserIssueCustomField.class, name = "SingleUserIssueCustomField"),
  @JsonSubTypes.Type(value = DateIssueCustomField.class, name = "DateIssueCustomField"),
  @JsonSubTypes.Type(value = SingleGroupIssueCustomField.class, name = "SingleGroupIssueCustomField"),
  @JsonSubTypes.Type(value = DatabaseMultiValueIssueCustomField.class, name = "DatabaseMultiValueIssueCustomField"),
  @JsonSubTypes.Type(value = SingleEnumIssueCustomField.class, name = "SingleEnumIssueCustomField"),
  @JsonSubTypes.Type(value = MultiOwnedIssueCustomField.class, name = "MultiOwnedIssueCustomField"),
  @JsonSubTypes.Type(value = TextIssueCustomField.class, name = "TextIssueCustomField"),
  @JsonSubTypes.Type(value = MultiVersionIssueCustomField.class, name = "MultiVersionIssueCustomField"),
  @JsonSubTypes.Type(value = MultiEnumIssueCustomField.class, name = "MultiEnumIssueCustomField"),
  @JsonSubTypes.Type(value = StateIssueCustomField.class, name = "StateIssueCustomField"),
  @JsonSubTypes.Type(value = SingleOwnedIssueCustomField.class, name = "SingleOwnedIssueCustomField"),
  @JsonSubTypes.Type(value = SimpleIssueCustomField.class, name = "SimpleIssueCustomField"),
  @JsonSubTypes.Type(value = MultiUserIssueCustomField.class, name = "MultiUserIssueCustomField"),
  @JsonSubTypes.Type(value = DatabaseSingleValueIssueCustomField.class, name = "DatabaseSingleValueIssueCustomField"),
  @JsonSubTypes.Type(value = MultiGroupIssueCustomField.class, name = "MultiGroupIssueCustomField"),
  @JsonSubTypes.Type(value = PeriodIssueCustomField.class, name = "PeriodIssueCustomField"),
  @JsonSubTypes.Type(value = SingleVersionIssueCustomField.class, name = "SingleVersionIssueCustomField"),
  @JsonSubTypes.Type(value = StateMachineIssueCustomField.class, name = "StateMachineIssueCustomField"),
})

public class IssueCustomField {
  @JsonProperty("id")
  private String id = null;

  @JsonTypeId
  private String $type = null;

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

   /**
   * Get $type
   * @return $type
  **/
  @Schema(description = "")
  public String get$Type() {
    return $type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueCustomField issueCustomField = (IssueCustomField) o;
    return Objects.equals(this.id, issueCustomField.id) &&
        Objects.equals(this.$type, issueCustomField.$type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, $type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueCustomField {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    $type: ").append(toIndentedString($type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
