/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2099.99
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package jetbrains.youtrack.client.api;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeId;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import io.swagger.v3.oas.annotations.media.Schema;

import static com.atlassian.renderer.v2.components.HtmlEscaper.escapeAll;

/**
 * Represents the command that was parsed from the provided query.
 */
@Schema(description = "Represents the command that was parsed from the provided query.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-04T14:25:38.465627+03:00[Europe/Moscow]")@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "$type", visible = true )
@JsonSubTypes({
})

public class ParsedCommand {
  @JsonProperty("description")
  private String description = null;

  @JsonProperty("error")
  private Boolean error = null;

  @JsonProperty("delete")
  private Boolean delete = null;

  @JsonProperty("id")
  private String id = null;

  @JsonTypeId
  private String $type = null;

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return escapeAll(description, false);
  }

   /**
   * Get error
   * @return error
  **/
  @Schema(description = "")
  public Boolean isError() {
    return error;
  }

   /**
   * Get delete
   * @return delete
  **/
  @Schema(description = "")
  public Boolean isDelete() {
    return delete;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

   /**
   * Get $type
   * @return $type
  **/
  @Schema(description = "")
  public String get$Type() {
    return $type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParsedCommand parsedCommand = (ParsedCommand) o;
    return Objects.equals(this.description, parsedCommand.description) &&
        Objects.equals(this.error, parsedCommand.error) &&
        Objects.equals(this.delete, parsedCommand.delete) &&
        Objects.equals(this.id, parsedCommand.id) &&
        Objects.equals(this.$type, parsedCommand.$type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, error, delete, id, $type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParsedCommand {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    delete: ").append(toIndentedString(delete)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    $type: ").append(toIndentedString($type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
