/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2099.99
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package jetbrains.youtrack.client.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Represents the period field in the issue.
 */
@Schema(description = "Represents the period field in the issue.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-04T14:25:38.465627+03:00[Europe/Moscow]")
public class PeriodIssueCustomField extends IssueCustomField implements ProjectCustomFieldAware {
  @JsonProperty("value")
  private PeriodValue value = null;
  @JsonProperty("projectCustomField")
  private ProjectCustomField projectCustomField = null;

  public PeriodIssueCustomField value(PeriodValue value) {
    this.value = value;
    return this;
  }

  public ProjectCustomField getProjectCustomField() {
    return projectCustomField;
  }

  public void setProjectCustomField(ProjectCustomField projectCustomField) {
    this.projectCustomField = projectCustomField;
  }

  /**
   * Get value
   * @return value
  **/
  @Schema(description = "")
  public PeriodValue getValue() {
    return value;
  }

  public void setValue(PeriodValue value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PeriodIssueCustomField periodIssueCustomField = (PeriodIssueCustomField) o;
    return Objects.equals(this.value, periodIssueCustomField.value) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PeriodIssueCustomField {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
