/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2099.99
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package jetbrains.youtrack.client.api;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Represents the field of simple type in the issue.
 */
@Schema(description = "Represents the field of simple type in the issue.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-04T14:25:38.465627+03:00[Europe/Moscow]")
public class SimpleIssueCustomField extends IssueCustomField implements ProjectCustomFieldAware {
  @JsonProperty("projectCustomField")
  private ProjectCustomField projectCustomField = null;

  @JsonProperty("value")
  private Object value = null;

  public SimpleIssueCustomField projectCustomField(ProjectCustomField projectCustomField) {
    this.projectCustomField = projectCustomField;
    return this;
  }

   /**
   * Get projectCustomField
   * @return projectCustomField
  **/
  @Schema(description = "")
  public ProjectCustomField getProjectCustomField() {
    return projectCustomField;
  }

  public void setProjectCustomField(ProjectCustomField projectCustomField) {
    this.projectCustomField = projectCustomField;
  }

   /**
   * Get value
   * @return value
  **/
  @Schema(description = "")
  public Object getValue() {
    return value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimpleIssueCustomField simpleIssueCustomField = (SimpleIssueCustomField) o;
    return Objects.equals(this.projectCustomField, simpleIssueCustomField.projectCustomField) &&
        Objects.equals(this.value, simpleIssueCustomField.value) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectCustomField, value, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimpleIssueCustomField {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    projectCustomField: ").append(toIndentedString(projectCustomField)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
