/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2099.99
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package jetbrains.youtrack.client.api;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import static com.atlassian.renderer.v2.components.HtmlEscaper.escapeAll;

/**
 * Represents the change of the boolean flag that indicates whether YouTrack Wiki or Markdown is used in the target entity as a markup language. If \&quot;true\&quot;, then the markdown is used. Otherwise, YouTrack Wiki markup.
 */
@Schema(description = "Represents the change of the boolean flag that indicates whether YouTrack Wiki or Markdown is used in the target entity as a markup language. If \"true\", then the markdown is used. Otherwise, YouTrack Wiki markup.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-04T14:25:38.465627+03:00[Europe/Moscow]")
public class UsesMarkupActivityItem extends SimpleValueActivityItem {
  @JsonProperty("removed")
  private Boolean removed = null;

  @JsonProperty("added")
  private Boolean added = null;

  @JsonProperty("markup")
  private String markup = null;

   /**
   * Get removed
   * @return removed
  **/
  @Schema(description = "")
  public Boolean isRemoved() {
    return removed;
  }

   /**
   * Get added
   * @return added
  **/
  @Schema(description = "")
  public Boolean isAdded() {
    return added;
  }

   /**
   * Get markup
   * @return markup
  **/
  @Schema(description = "")
  public String getMarkup() {
    return escapeAll(markup, false);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsesMarkupActivityItem usesMarkupActivityItem = (UsesMarkupActivityItem) o;
    return Objects.equals(this.removed, usesMarkupActivityItem.removed) &&
        Objects.equals(this.added, usesMarkupActivityItem.added) &&
        Objects.equals(this.markup, usesMarkupActivityItem.markup) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(removed, added, markup, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsesMarkupActivityItem {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    removed: ").append(toIndentedString(removed)).append("\n");
    sb.append("    added: ").append(toIndentedString(added)).append("\n");
    sb.append("    markup: ").append(toIndentedString(markup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
