/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2099.99
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package jetbrains.youtrack.client.api;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Represents the changes of properties responsible for visibility restriction. Can be &lt;a href&#x3D;\&quot;api-entity-VisibilityGroupActivityItem.xml\&quot;&gt;VisibilityGroupActivityItem&lt;/a&gt; or &lt;a href&#x3D;\&quot;api-entity-VisibilityUserActivityItem.xml\&quot;&gt;VisibilityUserActivityItem&lt;/a&gt;
 */
@Schema(description = "Represents the changes of properties responsible for visibility restriction. Can be <a href=\"api-entity-VisibilityGroupActivityItem.xml\">VisibilityGroupActivityItem</a> or <a href=\"api-entity-VisibilityUserActivityItem.xml\">VisibilityUserActivityItem</a>")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-04T14:25:38.465627+03:00[Europe/Moscow]")
public class VisibilityActivityItem extends MultiValueActivityItem {
  @JsonProperty("targetMember")
  private String targetMember = null;

   /**
   * Get targetMember
   * @return targetMember
  **/
  @Schema(description = "")
  public String getTargetMember() {
    return targetMember;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VisibilityActivityItem visibilityActivityItem = (VisibilityActivityItem) o;
    return Objects.equals(this.targetMember, visibilityActivityItem.targetMember) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(targetMember, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VisibilityActivityItem {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    targetMember: ").append(toIndentedString(targetMember)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
