/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2099.99
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package jetbrains.youtrack.client.api;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;

/**
 * Represents the event when a user adds or removes a group to/from the Visibility settings of the target entity.
 */
@Schema(description = "Represents the event when a user adds or removes a group to/from the Visibility settings of the target entity.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-04T14:25:38.465627+03:00[Europe/Moscow]")
public class VisibilityGroupActivityItem extends VisibilityActivityItem {
  @JsonProperty("targetMember")
  private String targetMember = null;

  @JsonProperty("targetSubMember")
  private String targetSubMember = null;

  @JsonProperty("removed")
  private List<UserGroup> removed = null;

  @JsonProperty("added")
  private List<UserGroup> added = null;

   /**
   * Get targetMember
   * @return targetMember
  **/
  @Schema(description = "")
  public String getTargetMember() {
    return targetMember;
  }

   /**
   * Get targetSubMember
   * @return targetSubMember
  **/
  @Schema(description = "")
  public String getTargetSubMember() {
    return targetSubMember;
  }

   /**
   * Get removed
   * @return removed
  **/
  @Schema(description = "")
  public List<UserGroup> getRemoved() {
    return removed;
  }

   /**
   * Get added
   * @return added
  **/
  @Schema(description = "")
  public List<UserGroup> getAdded() {
    return added;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VisibilityGroupActivityItem visibilityGroupActivityItem = (VisibilityGroupActivityItem) o;
    return Objects.equals(this.targetMember, visibilityGroupActivityItem.targetMember) &&
        Objects.equals(this.targetSubMember, visibilityGroupActivityItem.targetSubMember) &&
        Objects.equals(this.removed, visibilityGroupActivityItem.removed) &&
        Objects.equals(this.added, visibilityGroupActivityItem.added) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(targetMember, targetSubMember, removed, added, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VisibilityGroupActivityItem {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    targetMember: ").append(toIndentedString(targetMember)).append("\n");
    sb.append("    targetSubMember: ").append(toIndentedString(targetSubMember)).append("\n");
    sb.append("    removed: ").append(toIndentedString(removed)).append("\n");
    sb.append("    added: ").append(toIndentedString(added)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
